- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print course info
    ansible.builtin.debug:
        msg: "course name is : {{ COURSE }}, duration is: {{ DURATION }}, trainer is: {{ TRAINER }}"